### ISSUE TITLE
Why use weight as the font size variable name?

### ISSUE THREAD

**Issue by chaosgoo** [littlevgl/lv_lib_freetype#17]
In the lv_lib_freetype.h
````c
typedef struct {
    const char * name;  /* The name of the font file */
    lv_font_t * font;   /* point to lvgl font */
    uint16_t weight;    // HERE
    uint16_t style;     /* font style */  
} lv_ft_info_t;
````
But in th lv_lib_freetype.c
````c
// ...
dsc->height = info->weight;
// ...
scaler.width = info->weight;
scaler.height = info->weight;
// ...
````
Usually [Font weight](https://en.wikipedia.org/wiki/Font#Weight) has another meaning. Is it more appropriate to use  "size" here?
Like this
````c
typedef struct {
    const char * name;  /* The name of the font file */
    lv_font_t * font;   /* point to lvgl font */
    uint16_t size;    // HERE
    uint16_t style;     /* font style */  
} lv_ft_info_t;
````

**Comment by kisvegabor** [comment]
Thanks for pointing it out. Recently @guoweilkd worked a lot in FreeType integration. Hopefully he can tell more about it. 

FYI, it's called `weight` in the version in `lvgl` too.

**Comment by guoweilkd** [comment]
Sorry, this is a spelling mistake I made, and I would like to change its name, but considering the compatibility issue, I didn’t replace it with the correct word.

**Comment by chaosgoo** [comment]
> Sorry, this is a spelling mistake I made, and I would like to change its name, but considering the compatibility issue, I didn’t replace it with the correct word.

LOL. Thanks for your answer.
